#!/bin/bash
set -e

session="${AOC_SESSION_TOKEN}"
if [[ -z "${session}" ]];
then
  echo "aoc: $AOC_SESSION_TOKEN must be set. Get a token from authenticating at https://adventofcode.com"
  exit 1
fi

# year and specific day to setup
year=$1
day=$2
input_flag=$3
if [[ -z "${day}" ]] || [[ -z "${year}" ]];
then
  echo "usage: ./aoc <year> <day>."
  printf "\n\t--input: optional, retrieve the problem input"
  printf "\n\t--part2: update the problem text with part 2. Won't work until an answer has been accepted for part one."
  exit 2
fi

# validate problem actually exists
url="https://adventofcode.com/${year}/day/${day}"
curl -I --fail-with-body --silent --output /dev/null --show-error "${url}"

if [[ "${input_flag}" = "--input" ]];
then
  file="${year}/day${day}/input.txt"
  if [ -f "${file}" ];
  then
    echo "aoc: ${file} already exists."
    exit 65
  fi

  curl --cookie "session=${session}" "${url}/input" >> "${file}"
  exit 0
elif [[ "${input_flag}" = "--part2" ]];
then
  file="${year}/day${day}/problem.md"
  if [ -f "${file}" ];
  then
    rm "${file}"
  fi

  curl --cookie "session=${session}" --silent --show-error "${url}#part2" | pandoc -f html -t markdown >> "${file}"
  exit 0
fi

# setup year and day dirs
if [[ ! -d "${year}" ]];
then
  mkdir "${year}" && cd "$_" || exit 3
else
 cd "${year}"
fi

mkdir "day${day}"
cd "$_"

# basic go files
cat << EOF > main.go
package day${day}

EOF
cat << EOF > main_test.go
package day${day}

EOF

# tool for parsing problem text pages
parser="pandoc"
if ! brew list "${parser}" &>/dev/null; 
then
  brew install "${parser}"
fi

# get problem part 1 text
curl --cookie "session=${session}" --silent --show-error "${url}" | pandoc -f html -t markdown >> problem.md
echo "aoc: created files for problem ${url} in $(pwd)"